#!/usr/bin/env python3
"""
compile.py — the assess->enforce compiler for the mcp-gateway flavor.

Reads an mcp-reviewer `assessment.json` and emits pipelock policy configs (observe + enforce). Every rule
traces back to a review finding (provenance) — nobody else compiles a security review into runtime policy;
they all hand-author it. The ownable core is the engine-agnostic NEUTRAL CONTRACT; the pipelock rendering
is one adapter (a future ContextForge OPA/Rego adapter renders the same contract).

Design rules (security-agents ADR-0007; security-workflows plan Q3/Q4):
  * alert-only (warn) is the default; enforce (block) is the opt-in flip of the same policy.
  * a `deny` tool -> a block/warn rule; a `warn` tool -> always warn; an `allow` tool -> no rule (permitted).
  * observed egress -> the api_allowlist (least privilege from evidence).
  * server launch MUST resolve to an absolute local path, never a package runner (npx/uvx/bunx): hash-pinning
    only covers the runner binary, not the code it fetches at runtime (the supply-chain gap).

Usage: compile.py ASSESSMENT.json OUTDIR
  writes OUTDIR/{policy-contract.json, gateway.observe.yaml, gateway.enforce.yaml}

Dependency-free (stdlib only) so it runs anywhere the toolchain does.
"""
import json
import os
import re
import sys

RUNNERS = {"npx", "uvx", "bunx", "pnpx", "dlx"}


def die(msg):
    print(f"compile: error: {msg}", file=sys.stderr)
    sys.exit(2)


def load(path):
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        die(f"cannot read {path}: {e}")


def check_launch(server):
    """Enforce the absolute-local-path rule; reject package runners (the npx/uvx supply-chain gap)."""
    launch = server.get("launch") or {}
    cmd = str(launch.get("command", ""))
    if os.path.basename(cmd).lower() in RUNNERS:
        die(f"server.launch.command is a package runner ({cmd!r}); resolve it to an absolute local script "
            f"path (e.g. node /opt/app/server.js). Runners fetch remote code that hash-pinning cannot cover.")
    for a in launch.get("args", []):
        if os.path.basename(str(a)).lower() in RUNNERS:
            die(f"package runner {a!r} in server.launch.args; resolve to an absolute local path.")


def to_contract(a):
    """assessment.json -> the neutral, engine-agnostic policy contract (the ownable artifact)."""
    server = a.get("server") or {}
    check_launch(server)
    verdict_map = {"allow": "allow", "warn": "warn", "deny": "deny"}
    return {
        "contract": "mcp-runtime-policy/v0.1",
        "server": {
            "name": server.get("name", "unknown"),
            "launch": server.get("launch"),
            "sha256": server.get("sha256"),
            "approved": bool(server.get("approved", False)),
        },
        "tools": [
            {
                "name": t["name"],
                "action": verdict_map.get(t.get("verdict", "warn"), "warn"),
                "reason": t.get("reason", ""),
            }
            for t in (a.get("tools") or [])
        ],
        "egress": {
            "allow": list((a.get("egress") or {}).get("observed") or []),
            "deny_private": True,
            "block_metadata": True,
        },
        "dlp": {"block_on": list((a.get("dlp") or {}).get("block_on") or [])},
        "provenance": a.get("provenance") or {},
    }


def _yaml_str(s):
    """Emit a YAML-safe double-quoted scalar via JSON (JSON strings are valid YAML)."""
    return json.dumps(s, ensure_ascii=False)


def _rx_tool(name):
    """A pipelock tool_pattern that matches exactly this tool name (regex-escaped, case-insensitive)."""
    return "(?i)^" + re.sub(r"([.^$*+?()\[\]{}|\\])", r"\\\1", name) + "$"


def render_pipelock(contract, enforce):
    """neutral contract -> a pipelock.yaml (the adapter). enforce=True -> block, else warn (alert-only)."""
    act = "block" if enforce else "warn"
    mode = "strict" if enforce else "balanced"  # strict enforces api_allowlist at the allowlist layer
    prov = contract.get("provenance", {})
    server = contract["server"]
    sha = (server.get("sha256") or "?")
    out = [
        "# GENERATED by mcp-gateway compiler (compile.py) — do not hand-edit; regenerate from the assessment.",
        f"# Source assessment: {prov.get('assessment_id', '?')} "
        f"({prov.get('reviewer', '?')}, {prov.get('timestamp', '?')})",
        f"# Server: {server['name']}  sha256={sha[:16]}...  "
        f"mode={'ENFORCE (block)' if enforce else 'OBSERVE (alert-only)'}",
        "# Every rule below traces to a finding in that assessment (scan -> detonate -> enforce).",
        "",
        "version: 1",
        f"mode: {mode}",
        "",
        "# Egress allowlist = the destinations the review observed/approved. In ENFORCE (mode: strict) any",
        "# other host is blocked at the allowlist layer; in OBSERVE (mode: balanced) it is monitored (alert-only).",
        "api_allowlist:",
    ]
    out += [f"  - {_yaml_str(d)}" for d in contract["egress"]["allow"]] or ["  []"]
    out.append("")
    for sec in ("request_body_scanning", "response_scanning", "mcp_input_scanning", "mcp_tool_scanning"):
        out += [f"{sec}:", "  enabled: true", f"  action: {act}"]
    out += ["", "mcp_tool_policy:", "  enabled: true", f"  action: {act}"]
    rules = [t for t in contract["tools"] if t["action"] != "allow"]
    if rules:
        out.append("  rules:")
        for t in rules:
            rule_act = act if t["action"] == "deny" else "warn"  # 'warn' verdicts always alert, never hard-block
            out += [
                f"    - name: {_yaml_str((t['reason'] or t['name'])[:80])}",
                f"      tool_pattern: {_yaml_str(_rx_tool(t['name']))}",
                f"      action: {rule_act}",
            ]
    return "\n".join(out) + "\n"


def main():
    if len(sys.argv) != 3:
        die("usage: compile.py ASSESSMENT.json OUTDIR")
    contract = to_contract(load(sys.argv[1]))
    outdir = sys.argv[2]
    os.makedirs(outdir, exist_ok=True)
    with open(os.path.join(outdir, "policy-contract.json"), "w", encoding="utf-8") as f:
        json.dump(contract, f, indent=2)
        f.write("\n")
    with open(os.path.join(outdir, "gateway.observe.yaml"), "w", encoding="utf-8") as f:
        f.write(render_pipelock(contract, enforce=False))
    with open(os.path.join(outdir, "gateway.enforce.yaml"), "w", encoding="utf-8") as f:
        f.write(render_pipelock(contract, enforce=True))
    n_deny = sum(1 for t in contract["tools"] if t["action"] == "deny")
    n_warn = sum(1 for t in contract["tools"] if t["action"] == "warn")
    print(f"compiled {contract['server']['name']}: {len(contract['egress']['allow'])} egress-allow, "
          f"{n_deny} deny + {n_warn} warn tool rules "
          f"-> {outdir}/{{policy-contract.json, gateway.observe.yaml, gateway.enforce.yaml}}")


if __name__ == "__main__":
    main()
